package com.client.entity;

import java.util.Date;

public class Basket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basket.basket_id
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    private Integer basketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basket.user_id
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basket.goods_id
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basket.goods_count
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basket.basket_time
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    private Date basketTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basket.goods_total_price
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    private Float goodsTotalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basket.goods_size
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    private String goodsSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basket.basket_status
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    private Short basketStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basket.basket_id
     *
     * @return the value of basket.basket_id
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public Integer getBasketId() {
        return basketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basket.basket_id
     *
     * @param basketId the value for basket.basket_id
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public void setBasketId(Integer basketId) {
        this.basketId = basketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basket.user_id
     *
     * @return the value of basket.user_id
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basket.user_id
     *
     * @param userId the value for basket.user_id
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basket.goods_id
     *
     * @return the value of basket.goods_id
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basket.goods_id
     *
     * @param goodsId the value for basket.goods_id
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basket.goods_count
     *
     * @return the value of basket.goods_count
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basket.goods_count
     *
     * @param goodsCount the value for basket.goods_count
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basket.basket_time
     *
     * @return the value of basket.basket_time
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public Date getBasketTime() {
        return basketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basket.basket_time
     *
     * @param basketTime the value for basket.basket_time
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public void setBasketTime(Date basketTime) {
        this.basketTime = basketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basket.goods_total_price
     *
     * @return the value of basket.goods_total_price
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public Float getGoodsTotalPrice() {
        return goodsTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basket.goods_total_price
     *
     * @param goodsTotalPrice the value for basket.goods_total_price
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public void setGoodsTotalPrice(Float goodsTotalPrice) {
        this.goodsTotalPrice = goodsTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basket.goods_size
     *
     * @return the value of basket.goods_size
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public String getGoodsSize() {
        return goodsSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basket.goods_size
     *
     * @param goodsSize the value for basket.goods_size
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public void setGoodsSize(String goodsSize) {
        this.goodsSize = goodsSize == null ? null : goodsSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basket.basket_status
     *
     * @return the value of basket.basket_status
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public Short getBasketStatus() {
        return basketStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basket.basket_status
     *
     * @param basketStatus the value for basket.basket_status
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    public void setBasketStatus(Short basketStatus) {
        this.basketStatus = basketStatus;
    }
}