package com.client.entity;

import java.util.Date;

public class Collect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.collect_id
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    private Integer collectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.user_id
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.goods_id
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.collect_time
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    private Date collectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.is_exit
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    private String isExit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.collect_id
     *
     * @return the value of collect.collect_id
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    public Integer getCollectId() {
        return collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.collect_id
     *
     * @param collectId the value for collect.collect_id
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    public void setCollectId(Integer collectId) {
        this.collectId = collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.user_id
     *
     * @return the value of collect.user_id
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.user_id
     *
     * @param userId the value for collect.user_id
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.goods_id
     *
     * @return the value of collect.goods_id
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.goods_id
     *
     * @param goodsId the value for collect.goods_id
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.collect_time
     *
     * @return the value of collect.collect_time
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.collect_time
     *
     * @param collectTime the value for collect.collect_time
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.is_exit
     *
     * @return the value of collect.is_exit
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    public String getIsExit() {
        return isExit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.is_exit
     *
     * @param isExit the value for collect.is_exit
     *
     * @mbg.generated Mon Aug 27 08:40:35 CST 2018
     */
    public void setIsExit(String isExit) {
        this.isExit = isExit == null ? null : isExit.trim();
    }
}