package com.client.entity;

import java.util.Date;

public class FeedbackComment {
	private FeedbackComment feenbackComment;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_comment.fc_id
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    private Integer fcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_comment.order_user_id
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    private Integer orderUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_comment.feedback_content
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    private String feedbackContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_comment.feedback_time
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    private Date feedbackTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_comment.user_id
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_comment.fc_id
     *
     * @return the value of feedback_comment.fc_id
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    public Integer getFcId() {
        return fcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_comment.fc_id
     *
     * @param fcId the value for feedback_comment.fc_id
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    public void setFcId(Integer fcId) {
        this.fcId = fcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_comment.order_user_id
     *
     * @return the value of feedback_comment.order_user_id
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    public Integer getOrderUserId() {
        return orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_comment.order_user_id
     *
     * @param orderUserId the value for feedback_comment.order_user_id
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    public void setOrderUserId(Integer orderUserId) {
        this.orderUserId = orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_comment.feedback_content
     *
     * @return the value of feedback_comment.feedback_content
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    public String getFeedbackContent() {
        return feedbackContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_comment.feedback_content
     *
     * @param feedbackContent the value for feedback_comment.feedback_content
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    public void setFeedbackContent(String feedbackContent) {
        this.feedbackContent = feedbackContent == null ? null : feedbackContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_comment.feedback_time
     *
     * @return the value of feedback_comment.feedback_time
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    public Date getFeedbackTime() {
        return feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_comment.feedback_time
     *
     * @param feedbackTime the value for feedback_comment.feedback_time
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    public void setFeedbackTime(Date feedbackTime) {
        this.feedbackTime = feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_comment.user_id
     *
     * @return the value of feedback_comment.user_id
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_comment.user_id
     *
     * @param userId the value for feedback_comment.user_id
     *
     * @mbg.generated Fri Aug 10 16:10:27 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

	public FeedbackComment getFeenbackComment() {
		return feenbackComment;
	}

	public void setFeenbackComment(FeedbackComment feenbackComment) {
		this.feenbackComment = feenbackComment;
	}
    
    
}