package com.client.entity;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_sales_volume
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    private Integer goodsSalesVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_inventory
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    private Integer goodsInventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_price
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    private Float goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_middle_price
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    private Float goodsMiddlePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_describe
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    private String goodsDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_picture
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    private String goodsPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_is_sale
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    private String goodsIsSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_type
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    private Integer goodsType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_id
     *
     * @return the value of goods.goods_id
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_id
     *
     * @param goodsId the value for goods.goods_id
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goodsName the value for goods.goods_name
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_sales_volume
     *
     * @return the value of goods.goods_sales_volume
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public Integer getGoodsSalesVolume() {
        return goodsSalesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_sales_volume
     *
     * @param goodsSalesVolume the value for goods.goods_sales_volume
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public void setGoodsSalesVolume(Integer goodsSalesVolume) {
        this.goodsSalesVolume = goodsSalesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_inventory
     *
     * @return the value of goods.goods_inventory
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public Integer getGoodsInventory() {
        return goodsInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_inventory
     *
     * @param goodsInventory the value for goods.goods_inventory
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public void setGoodsInventory(Integer goodsInventory) {
        this.goodsInventory = goodsInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_price
     *
     * @return the value of goods.goods_price
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public Float getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_price
     *
     * @param goodsPrice the value for goods.goods_price
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public void setGoodsPrice(Float goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_middle_price
     *
     * @return the value of goods.goods_middle_price
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public Float getGoodsMiddlePrice() {
        return goodsMiddlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_middle_price
     *
     * @param goodsMiddlePrice the value for goods.goods_middle_price
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public void setGoodsMiddlePrice(Float goodsMiddlePrice) {
        this.goodsMiddlePrice = goodsMiddlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_describe
     *
     * @return the value of goods.goods_describe
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public String getGoodsDescribe() {
        return goodsDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_describe
     *
     * @param goodsDescribe the value for goods.goods_describe
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public void setGoodsDescribe(String goodsDescribe) {
        this.goodsDescribe = goodsDescribe == null ? null : goodsDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_picture
     *
     * @return the value of goods.goods_picture
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public String getGoodsPicture() {
        return goodsPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_picture
     *
     * @param goodsPicture the value for goods.goods_picture
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public void setGoodsPicture(String goodsPicture) {
        this.goodsPicture = goodsPicture == null ? null : goodsPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_is_sale
     *
     * @return the value of goods.goods_is_sale
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public String getGoodsIsSale() {
        return goodsIsSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_is_sale
     *
     * @param goodsIsSale the value for goods.goods_is_sale
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public void setGoodsIsSale(String goodsIsSale) {
        this.goodsIsSale = goodsIsSale == null ? null : goodsIsSale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_type
     *
     * @return the value of goods.goods_type
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public Integer getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_type
     *
     * @param goodsType the value for goods.goods_type
     *
     * @mbg.generated Sat Jul 21 11:48:28 CST 2018
     */
    public void setGoodsType(Integer goodsType) {
        this.goodsType = goodsType;
    }
}