package com.client.entity;

public class Goodstype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.gt_id
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    private Integer gtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.gt_name
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    private String gtName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.gt_id
     *
     * @return the value of goods_type.gt_id
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    public Integer getGtId() {
        return gtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.gt_id
     *
     * @param gtId the value for goods_type.gt_id
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    public void setGtId(Integer gtId) {
        this.gtId = gtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.gt_name
     *
     * @return the value of goods_type.gt_name
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    public String getGtName() {
        return gtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.gt_name
     *
     * @param gtName the value for goods_type.gt_name
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    public void setGtName(String gtName) {
        this.gtName = gtName == null ? null : gtName.trim();
    }
}