package com.client.entity;

import java.util.Date;

public class IntegralOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_order.integral_order_id
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    private Integer integralOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_order.shop_id
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_order.user_id
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_order.order_time
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    private String orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_order.order_status
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    private Short orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_order.is_exit
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    private String isExit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_order.delivery_time
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    private String deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_order.address
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_order.confirm_receipt_time
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    private Date confirmReceiptTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_order.integral_order_id
     *
     * @return the value of integral_order.integral_order_id
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public Integer getIntegralOrderId() {
        return integralOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_order.integral_order_id
     *
     * @param integralOrderId the value for integral_order.integral_order_id
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public void setIntegralOrderId(Integer integralOrderId) {
        this.integralOrderId = integralOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_order.shop_id
     *
     * @return the value of integral_order.shop_id
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_order.shop_id
     *
     * @param shopId the value for integral_order.shop_id
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_order.user_id
     *
     * @return the value of integral_order.user_id
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_order.user_id
     *
     * @param userId the value for integral_order.user_id
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_order.order_time
     *
     * @return the value of integral_order.order_time
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_order.order_time
     *
     * @param orderTime the value for integral_order.order_time
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_order.order_status
     *
     * @return the value of integral_order.order_status
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public Short getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_order.order_status
     *
     * @param orderStatus the value for integral_order.order_status
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public void setOrderStatus(Short orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_order.is_exit
     *
     * @return the value of integral_order.is_exit
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public String getIsExit() {
        return isExit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_order.is_exit
     *
     * @param isExit the value for integral_order.is_exit
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public void setIsExit(String isExit) {
        this.isExit = isExit == null ? null : isExit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_order.delivery_time
     *
     * @return the value of integral_order.delivery_time
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_order.delivery_time
     *
     * @param deliveryTime the value for integral_order.delivery_time
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime == null ? null : deliveryTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_order.address
     *
     * @return the value of integral_order.address
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_order.address
     *
     * @param address the value for integral_order.address
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_order.confirm_receipt_time
     *
     * @return the value of integral_order.confirm_receipt_time
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public Date getConfirmReceiptTime() {
        return confirmReceiptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_order.confirm_receipt_time
     *
     * @param confirmReceiptTime the value for integral_order.confirm_receipt_time
     *
     * @mbg.generated Wed Aug 29 16:38:53 CST 2018
     */
    public void setConfirmReceiptTime(Date confirmReceiptTime) {
        this.confirmReceiptTime = confirmReceiptTime;
    }
}