package com.client.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IntegralFeedbackCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public IntegralFeedbackCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIfcIdIsNull() {
            addCriterion("ifc_id is null");
            return (Criteria) this;
        }

        public Criteria andIfcIdIsNotNull() {
            addCriterion("ifc_id is not null");
            return (Criteria) this;
        }

        public Criteria andIfcIdEqualTo(Integer value) {
            addCriterion("ifc_id =", value, "ifcId");
            return (Criteria) this;
        }

        public Criteria andIfcIdNotEqualTo(Integer value) {
            addCriterion("ifc_id <>", value, "ifcId");
            return (Criteria) this;
        }

        public Criteria andIfcIdGreaterThan(Integer value) {
            addCriterion("ifc_id >", value, "ifcId");
            return (Criteria) this;
        }

        public Criteria andIfcIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ifc_id >=", value, "ifcId");
            return (Criteria) this;
        }

        public Criteria andIfcIdLessThan(Integer value) {
            addCriterion("ifc_id <", value, "ifcId");
            return (Criteria) this;
        }

        public Criteria andIfcIdLessThanOrEqualTo(Integer value) {
            addCriterion("ifc_id <=", value, "ifcId");
            return (Criteria) this;
        }

        public Criteria andIfcIdIn(List<Integer> values) {
            addCriterion("ifc_id in", values, "ifcId");
            return (Criteria) this;
        }

        public Criteria andIfcIdNotIn(List<Integer> values) {
            addCriterion("ifc_id not in", values, "ifcId");
            return (Criteria) this;
        }

        public Criteria andIfcIdBetween(Integer value1, Integer value2) {
            addCriterion("ifc_id between", value1, value2, "ifcId");
            return (Criteria) this;
        }

        public Criteria andIfcIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ifc_id not between", value1, value2, "ifcId");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdIsNull() {
            addCriterion("integral_order_id is null");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdIsNotNull() {
            addCriterion("integral_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdEqualTo(Integer value) {
            addCriterion("integral_order_id =", value, "integralOrderId");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdNotEqualTo(Integer value) {
            addCriterion("integral_order_id <>", value, "integralOrderId");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdGreaterThan(Integer value) {
            addCriterion("integral_order_id >", value, "integralOrderId");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("integral_order_id >=", value, "integralOrderId");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdLessThan(Integer value) {
            addCriterion("integral_order_id <", value, "integralOrderId");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("integral_order_id <=", value, "integralOrderId");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdIn(List<Integer> values) {
            addCriterion("integral_order_id in", values, "integralOrderId");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdNotIn(List<Integer> values) {
            addCriterion("integral_order_id not in", values, "integralOrderId");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("integral_order_id between", value1, value2, "integralOrderId");
            return (Criteria) this;
        }

        public Criteria andIntegralOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("integral_order_id not between", value1, value2, "integralOrderId");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentIsNull() {
            addCriterion("feedback_content is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentIsNotNull() {
            addCriterion("feedback_content is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentEqualTo(String value) {
            addCriterion("feedback_content =", value, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentNotEqualTo(String value) {
            addCriterion("feedback_content <>", value, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentGreaterThan(String value) {
            addCriterion("feedback_content >", value, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentGreaterThanOrEqualTo(String value) {
            addCriterion("feedback_content >=", value, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentLessThan(String value) {
            addCriterion("feedback_content <", value, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentLessThanOrEqualTo(String value) {
            addCriterion("feedback_content <=", value, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentLike(String value) {
            addCriterion("feedback_content like", value, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentNotLike(String value) {
            addCriterion("feedback_content not like", value, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentIn(List<String> values) {
            addCriterion("feedback_content in", values, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentNotIn(List<String> values) {
            addCriterion("feedback_content not in", values, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentBetween(String value1, String value2) {
            addCriterion("feedback_content between", value1, value2, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackContentNotBetween(String value1, String value2) {
            addCriterion("feedback_content not between", value1, value2, "feedbackContent");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeIsNull() {
            addCriterion("feedback_time is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeIsNotNull() {
            addCriterion("feedback_time is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeEqualTo(Date value) {
            addCriterion("feedback_time =", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeNotEqualTo(Date value) {
            addCriterion("feedback_time <>", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeGreaterThan(Date value) {
            addCriterion("feedback_time >", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("feedback_time >=", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeLessThan(Date value) {
            addCriterion("feedback_time <", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeLessThanOrEqualTo(Date value) {
            addCriterion("feedback_time <=", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeIn(List<Date> values) {
            addCriterion("feedback_time in", values, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeNotIn(List<Date> values) {
            addCriterion("feedback_time not in", values, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeBetween(Date value1, Date value2) {
            addCriterion("feedback_time between", value1, value2, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeNotBetween(Date value1, Date value2) {
            addCriterion("feedback_time not between", value1, value2, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 26 07:59:05 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table integral_feedback_comment
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}