package com.client.entity;

import java.util.Date;

public class IntegralFeedbackComment {
	private IntegralFeedbackComment integralFeedbackComment;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_feedback_comment.ifc_id
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    private Integer ifcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_feedback_comment.integral_order_id
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    private Integer integralOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_feedback_comment.feedback_content
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    private String feedbackContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_feedback_comment.feedback_time
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    private Date feedbackTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_feedback_comment.user_id
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_feedback_comment.ifc_id
     *
     * @return the value of integral_feedback_comment.ifc_id
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public Integer getIfcId() {
        return ifcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_feedback_comment.ifc_id
     *
     * @param ifcId the value for integral_feedback_comment.ifc_id
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public void setIfcId(Integer ifcId) {
        this.ifcId = ifcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_feedback_comment.integral_order_id
     *
     * @return the value of integral_feedback_comment.integral_order_id
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public Integer getIntegralOrderId() {
        return integralOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_feedback_comment.integral_order_id
     *
     * @param integralOrderId the value for integral_feedback_comment.integral_order_id
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public void setIntegralOrderId(Integer integralOrderId) {
        this.integralOrderId = integralOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_feedback_comment.feedback_content
     *
     * @return the value of integral_feedback_comment.feedback_content
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public String getFeedbackContent() {
        return feedbackContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_feedback_comment.feedback_content
     *
     * @param feedbackContent the value for integral_feedback_comment.feedback_content
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public void setFeedbackContent(String feedbackContent) {
        this.feedbackContent = feedbackContent == null ? null : feedbackContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_feedback_comment.feedback_time
     *
     * @return the value of integral_feedback_comment.feedback_time
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public Date getFeedbackTime() {
        return feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_feedback_comment.feedback_time
     *
     * @param feedbackTime the value for integral_feedback_comment.feedback_time
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public void setFeedbackTime(Date feedbackTime) {
        this.feedbackTime = feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_feedback_comment.user_id
     *
     * @return the value of integral_feedback_comment.user_id
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_feedback_comment.user_id
     *
     * @param userId the value for integral_feedback_comment.user_id
     *
     * @mbg.generated Sun Aug 26 07:59:05 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

	public IntegralFeedbackComment getIntegralFeedbackComment() {
		return integralFeedbackComment;
	}

	public void setIntegralFeedbackComment(IntegralFeedbackComment integralFeedbackComment) {
		this.integralFeedbackComment = integralFeedbackComment;
	}
    
    
}