package com.client.entity;

public class OrderUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user.order_user_id
     *
     * @mbg.generated Sat Aug 04 08:26:36 CST 2018
     */
    private Integer orderUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_user.user_id
     *
     * @mbg.generated Sat Aug 04 08:26:36 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user.order_user_id
     *
     * @return the value of order_user.order_user_id
     *
     * @mbg.generated Sat Aug 04 08:26:36 CST 2018
     */
    public Integer getOrderUserId() {
        return orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user.order_user_id
     *
     * @param orderUserId the value for order_user.order_user_id
     *
     * @mbg.generated Sat Aug 04 08:26:36 CST 2018
     */
    public void setOrderUserId(Integer orderUserId) {
        this.orderUserId = orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_user.user_id
     *
     * @return the value of order_user.user_id
     *
     * @mbg.generated Sat Aug 04 08:26:36 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_user.user_id
     *
     * @param userId the value for order_user.user_id
     *
     * @mbg.generated Sat Aug 04 08:26:36 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}