package com.client.entity;

public class OrderStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_status.status_id
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    private Short statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_status.status_name
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    private String statusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_status.status_id
     *
     * @return the value of order_status.status_id
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    public Short getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_status.status_id
     *
     * @param statusId the value for order_status.status_id
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    public void setStatusId(Short statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_status.status_name
     *
     * @return the value of order_status.status_name
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_status.status_name
     *
     * @param statusName the value for order_status.status_name
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }
}