package com.client.entity;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_user_id
     *
     * @mbg.generated Sat Aug 04 07:40:16 CST 2018
     */
    private Integer orderUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_goods_id
     *
     * @mbg.generated Sat Aug 04 07:40:16 CST 2018
     */
    private Integer orderGoodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_user_id
     *
     * @return the value of orders.order_user_id
     *
     * @mbg.generated Sat Aug 04 07:40:16 CST 2018
     */
    public Integer getOrderUserId() {
        return orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_user_id
     *
     * @param orderUserId the value for orders.order_user_id
     *
     * @mbg.generated Sat Aug 04 07:40:16 CST 2018
     */
    public void setOrderUserId(Integer orderUserId) {
        this.orderUserId = orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_goods_id
     *
     * @return the value of orders.order_goods_id
     *
     * @mbg.generated Sat Aug 04 07:40:16 CST 2018
     */
    public Integer getOrderGoodsId() {
        return orderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_goods_id
     *
     * @param orderGoodsId the value for orders.order_goods_id
     *
     * @mbg.generated Sat Aug 04 07:40:16 CST 2018
     */
    public void setOrderGoodsId(Integer orderGoodsId) {
        this.orderGoodsId = orderGoodsId;
    }
}