package com.client.entity;


public class OrderGoods {
	private Goods goods;
	private Goodstype goodsType;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_goods_id
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    private Integer orderGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_id
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_count
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    private Short goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_total_price
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    private Float goodsTotalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_size
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    private String goodsSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_remarks
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    private String goodsRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_goods_id
     *
     * @return the value of order_goods.order_goods_id
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public Integer getOrderGoodsId() {
        return orderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_goods_id
     *
     * @param orderGoodsId the value for order_goods.order_goods_id
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public void setOrderGoodsId(Integer orderGoodsId) {
        this.orderGoodsId = orderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_id
     *
     * @return the value of order_goods.goods_id
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_id
     *
     * @param goodsId the value for order_goods.goods_id
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_count
     *
     * @return the value of order_goods.goods_count
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public Short getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_count
     *
     * @param goodsCount the value for order_goods.goods_count
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public void setGoodsCount(Short goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_total_price
     *
     * @return the value of order_goods.goods_total_price
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public Float getGoodsTotalPrice() {
        return goodsTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_total_price
     *
     * @param goodsTotalPrice the value for order_goods.goods_total_price
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public void setGoodsTotalPrice(Float goodsTotalPrice) {
        this.goodsTotalPrice = goodsTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_size
     *
     * @return the value of order_goods.goods_size
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public String getGoodsSize() {
        return goodsSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_size
     *
     * @param goodsSize the value for order_goods.goods_size
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public void setGoodsSize(String goodsSize) {
        this.goodsSize = goodsSize == null ? null : goodsSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_remarks
     *
     * @return the value of order_goods.goods_remarks
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public String getGoodsRemarks() {
        return goodsRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_remarks
     *
     * @param goodsRemarks the value for order_goods.goods_remarks
     *
     * @mbg.generated Thu Aug 16 12:19:20 CST 2018
     */
    public void setGoodsRemarks(String goodsRemarks) {
        this.goodsRemarks = goodsRemarks == null ? null : goodsRemarks.trim();
    }

	public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Goodstype getGoodsType() {
		return goodsType;
	}

	public void setGoodsType(Goodstype goodsType) {
		this.goodsType = goodsType;
	}

	
    
    
}