package com.client.entity;

public class Recommend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.recommend_id
     *
     * @mbg.generated Sun Jul 22 07:49:05 CST 2018
     */
    private Integer recommendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.goods_id
     *
     * @mbg.generated Sun Jul 22 07:49:05 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.is_sale
     *
     * @mbg.generated Sun Jul 22 07:49:05 CST 2018
     */
    private String isSale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.recommend_id
     *
     * @return the value of recommend.recommend_id
     *
     * @mbg.generated Sun Jul 22 07:49:05 CST 2018
     */
    public Integer getRecommendId() {
        return recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.recommend_id
     *
     * @param recommendId the value for recommend.recommend_id
     *
     * @mbg.generated Sun Jul 22 07:49:05 CST 2018
     */
    public void setRecommendId(Integer recommendId) {
        this.recommendId = recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.goods_id
     *
     * @return the value of recommend.goods_id
     *
     * @mbg.generated Sun Jul 22 07:49:05 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.goods_id
     *
     * @param goodsId the value for recommend.goods_id
     *
     * @mbg.generated Sun Jul 22 07:49:05 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.is_sale
     *
     * @return the value of recommend.is_sale
     *
     * @mbg.generated Sun Jul 22 07:49:05 CST 2018
     */
    public String getIsSale() {
        return isSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.is_sale
     *
     * @param isSale the value for recommend.is_sale
     *
     * @mbg.generated Sun Jul 22 07:49:05 CST 2018
     */
    public void setIsSale(String isSale) {
        this.isSale = isSale == null ? null : isSale.trim();
    }
}