package com.client.entity;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_id
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.goods_id
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.integral
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.is_sale
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    private String isSale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_id
     *
     * @return the value of shop.shop_id
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_id
     *
     * @param shopId the value for shop.shop_id
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.goods_id
     *
     * @return the value of shop.goods_id
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.goods_id
     *
     * @param goodsId the value for shop.goods_id
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.integral
     *
     * @return the value of shop.integral
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.integral
     *
     * @param integral the value for shop.integral
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.is_sale
     *
     * @return the value of shop.is_sale
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    public String getIsSale() {
        return isSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.is_sale
     *
     * @param isSale the value for shop.is_sale
     *
     * @mbg.generated Sat Jul 21 21:44:28 CST 2018
     */
    public void setIsSale(String isSale) {
        this.isSale = isSale == null ? null : isSale.trim();
    }
}