package com.client.entity;

import java.util.Date;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_id
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_name
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_email
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_sex
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private String userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_password
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_phone
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_address
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private String userAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_photo
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private String userPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.register_time
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_integral
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private Integer userIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.last_login_time
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_address2
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private String userAddress2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_address3
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    private String userAddress3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_id
     *
     * @return the value of userinfo.user_id
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_id
     *
     * @param userId the value for userinfo.user_id
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_name
     *
     * @return the value of userinfo.user_name
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_name
     *
     * @param userName the value for userinfo.user_name
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_email
     *
     * @return the value of userinfo.user_email
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_email
     *
     * @param userEmail the value for userinfo.user_email
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_sex
     *
     * @return the value of userinfo.user_sex
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_sex
     *
     * @param userSex the value for userinfo.user_sex
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_password
     *
     * @return the value of userinfo.user_password
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_password
     *
     * @param userPassword the value for userinfo.user_password
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_phone
     *
     * @return the value of userinfo.user_phone
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_phone
     *
     * @param userPhone the value for userinfo.user_phone
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_address
     *
     * @return the value of userinfo.user_address
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_address
     *
     * @param userAddress the value for userinfo.user_address
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_photo
     *
     * @return the value of userinfo.user_photo
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public String getUserPhoto() {
        return userPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_photo
     *
     * @param userPhoto the value for userinfo.user_photo
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserPhoto(String userPhoto) {
        this.userPhoto = userPhoto == null ? null : userPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.register_time
     *
     * @return the value of userinfo.register_time
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.register_time
     *
     * @param registerTime the value for userinfo.register_time
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_integral
     *
     * @return the value of userinfo.user_integral
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public Integer getUserIntegral() {
        return userIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_integral
     *
     * @param userIntegral the value for userinfo.user_integral
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserIntegral(Integer userIntegral) {
        this.userIntegral = userIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.last_login_time
     *
     * @return the value of userinfo.last_login_time
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.last_login_time
     *
     * @param lastLoginTime the value for userinfo.last_login_time
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_address2
     *
     * @return the value of userinfo.user_address2
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public String getUserAddress2() {
        return userAddress2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_address2
     *
     * @param userAddress2 the value for userinfo.user_address2
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserAddress2(String userAddress2) {
        this.userAddress2 = userAddress2 == null ? null : userAddress2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_address3
     *
     * @return the value of userinfo.user_address3
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public String getUserAddress3() {
        return userAddress3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_address3
     *
     * @param userAddress3 the value for userinfo.user_address3
     *
     * @mbg.generated Mon Aug 13 22:43:07 CST 2018
     */
    public void setUserAddress3(String userAddress3) {
        this.userAddress3 = userAddress3 == null ? null : userAddress3.trim();
    }
}