package com.management.entity;

public class BlackList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.bl_id
     *
     * @mbg.generated Sun Nov 18 10:15:31 CST 2018
     */
    private Integer blId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.user_id
     *
     * @mbg.generated Sun Nov 18 10:15:31 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.bl_id
     *
     * @return the value of blacklist.bl_id
     *
     * @mbg.generated Sun Nov 18 10:15:31 CST 2018
     */
    public Integer getBlId() {
        return blId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.bl_id
     *
     * @param blId the value for blacklist.bl_id
     *
     * @mbg.generated Sun Nov 18 10:15:31 CST 2018
     */
    public void setBlId(Integer blId) {
        this.blId = blId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.user_id
     *
     * @return the value of blacklist.user_id
     *
     * @mbg.generated Sun Nov 18 10:15:31 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.user_id
     *
     * @param userId the value for blacklist.user_id
     *
     * @mbg.generated Sun Nov 18 10:15:31 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}