package com.management.entity;

import java.util.Date;

public class Managerinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managerinfo.manager_id
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managerinfo.manager_name
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managerinfo.manager_password
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    private String managerPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managerinfo.manager_phone
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    private String managerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managerinfo.manager_photo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    private String managerPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managerinfo.is_exist
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    private String isExist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managerinfo.register_time
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managerinfo.login_time
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managerinfo.manager_id
     *
     * @return the value of managerinfo.manager_id
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managerinfo.manager_id
     *
     * @param managerId the value for managerinfo.manager_id
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managerinfo.manager_name
     *
     * @return the value of managerinfo.manager_name
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managerinfo.manager_name
     *
     * @param managerName the value for managerinfo.manager_name
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managerinfo.manager_password
     *
     * @return the value of managerinfo.manager_password
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public String getManagerPassword() {
        return managerPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managerinfo.manager_password
     *
     * @param managerPassword the value for managerinfo.manager_password
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public void setManagerPassword(String managerPassword) {
        this.managerPassword = managerPassword == null ? null : managerPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managerinfo.manager_phone
     *
     * @return the value of managerinfo.manager_phone
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public String getManagerPhone() {
        return managerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managerinfo.manager_phone
     *
     * @param managerPhone the value for managerinfo.manager_phone
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone == null ? null : managerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managerinfo.manager_photo
     *
     * @return the value of managerinfo.manager_photo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public String getManagerPhoto() {
        return managerPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managerinfo.manager_photo
     *
     * @param managerPhoto the value for managerinfo.manager_photo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public void setManagerPhoto(String managerPhoto) {
        this.managerPhoto = managerPhoto == null ? null : managerPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managerinfo.is_exist
     *
     * @return the value of managerinfo.is_exist
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public String getIsExist() {
        return isExist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managerinfo.is_exist
     *
     * @param isExist the value for managerinfo.is_exist
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public void setIsExist(String isExist) {
        this.isExist = isExist == null ? null : isExist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managerinfo.register_time
     *
     * @return the value of managerinfo.register_time
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managerinfo.register_time
     *
     * @param registerTime the value for managerinfo.register_time
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managerinfo.login_time
     *
     * @return the value of managerinfo.login_time
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managerinfo.login_time
     *
     * @param loginTime the value for managerinfo.login_time
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}