package com.management.dao;

import com.management.entity.Managerinfo;
import com.management.entity.ManagerinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    long countByExample(ManagerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    int deleteByExample(ManagerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    int deleteByPrimaryKey(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    int insert(Managerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    int insertSelective(Managerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    List<Managerinfo> selectByExample(ManagerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    Managerinfo selectByPrimaryKey(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") Managerinfo record, @Param("example") ManagerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    int updateByExample(@Param("record") Managerinfo record, @Param("example") ManagerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    int updateByPrimaryKeySelective(Managerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated Sat Sep 08 15:24:44 CST 2018
     */
    int updateByPrimaryKey(Managerinfo record);
}