package com.management.dao;

import com.management.entity.OtherProject;
import com.management.entity.OtherProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OtherProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    long countByExample(OtherProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    int deleteByExample(OtherProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    int deleteByPrimaryKey(Integer opId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    int insert(OtherProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    int insertSelective(OtherProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    List<OtherProject> selectByExample(OtherProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    OtherProject selectByPrimaryKey(Integer opId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") OtherProject record, @Param("example") OtherProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    int updateByExample(@Param("record") OtherProject record, @Param("example") OtherProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    int updateByPrimaryKeySelective(OtherProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_project
     *
     * @mbg.generated Fri Sep 07 11:06:15 CST 2018
     */
    int updateByPrimaryKey(OtherProject record);
}