package com.client.dao;

import com.client.entity.Basket;
import com.client.entity.BasketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    long countByExample(BasketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    int deleteByExample(BasketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    int deleteByPrimaryKey(Integer basketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    int insert(Basket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    int insertSelective(Basket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    List<Basket> selectByExample(BasketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    Basket selectByPrimaryKey(Integer basketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Basket record, @Param("example") BasketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    int updateByExample(@Param("record") Basket record, @Param("example") BasketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    int updateByPrimaryKeySelective(Basket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basket
     *
     * @mbg.generated Wed Aug 08 09:27:39 CST 2018
     */
    int updateByPrimaryKey(Basket record);
}