package com.client.dao;

import com.client.entity.Goodstype;
import com.client.entity.GoodstypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    long countByExample(GoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    int deleteByExample(GoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    int deleteByPrimaryKey(Integer gtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    int insert(Goodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    int insertSelective(Goodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    List<Goodstype> selectByExample(GoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    Goodstype selectByPrimaryKey(Integer gtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") Goodstype record, @Param("example") GoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    int updateByExample(@Param("record") Goodstype record, @Param("example") GoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    int updateByPrimaryKeySelective(Goodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Sat Jul 21 13:04:03 CST 2018
     */
    int updateByPrimaryKey(Goodstype record);
}