package com.client.dao;

import com.client.entity.OrderStatus;
import com.client.entity.OrderStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    long countByExample(OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    int deleteByExample(OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    int deleteByPrimaryKey(Short statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    int insert(OrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    int insertSelective(OrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    List<OrderStatus> selectByExample(OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    OrderStatus selectByPrimaryKey(Short statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderStatus record, @Param("example") OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    int updateByExample(@Param("record") OrderStatus record, @Param("example") OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    int updateByPrimaryKeySelective(OrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Wed Aug 01 22:09:05 CST 2018
     */
    int updateByPrimaryKey(OrderStatus record);
}