package com.client.dao;

import com.client.entity.Signin;
import com.client.entity.SigninExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SigninMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    long countByExample(SigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    int deleteByExample(SigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    int deleteByPrimaryKey(Integer signinId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    int insert(Signin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    int insertSelective(Signin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    List<Signin> selectByExample(SigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    Signin selectByPrimaryKey(Integer signinId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") Signin record, @Param("example") SigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    int updateByExample(@Param("record") Signin record, @Param("example") SigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    int updateByPrimaryKeySelective(Signin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Aug 01 22:10:16 CST 2018
     */
    int updateByPrimaryKey(Signin record);
}